// const people = ["Greg", "Mary", "Devon", "James"];

// people.shift()

// people[people.length-1]= "Jason"
// people.push("itai")

// let favorite = people.slice(1,people.length)

// console.log(favorite)

// for (i in people)
//     {
//         console.log(people[i])

//         if(ppeople[i]="Devon"){
//             break
//         }
//     }
// colors= ["blue", "green"]
// for (let i in colors)
// {
//     console.log( "My #" + (i+1) + " Choice is " + colors[i])
// }


// let i = 0;
// do {
//  i= prompt("Pick a number:")
// }
// while (i < 10);

// let family = {
//     dad:1,
//     cousins:3,
//     siblings:10
// }
// for (member in family) {
//     console.log(family[member])
// }

// const details = {
//     my: 'name',
//     is: 'Rudolf',
//     the: 'raindeer'
// }

// const names = ["Jack", "Philip", "Sarah", "Amanda", "Bernard", "Kyle"];
// secretName=""
// for (i in names)
//     {
//         secretName+= names[i][0]

        
//     }
//     function sortAlpha(word) {
//         return word.split("")
//                    .sort()
//                    .join("");
//     }
     
//     console.log(sortAlpha(secretName))

// const building = {
//     numberOfFloors: 4,
//     numberOfAptByFloor: {
//         firstFloor: 3,
//         secondFloor: 4,
//         thirdFloor: 9,
//         fourthFloor: 2,
//     },
//     nameOfTenants: ["Sarah", "Dan", "David"],
//     numberOfRoomsAndRent:  {
//         sarah: [3, 990],
//         dan:  [4, 1000],
//         david: [1, 500],
//     },
// }

// console.log(building.numberOfRoomsAndRent['dan'][0])
